### PR TITLE
Fix type conversion of CLI options

### LINKED ISSUE #283: Doctrine ORM Manager named "" does not exist.
After upgrading from `2.0.0` to the latest `2.1.0` today, migration commands stoped working.
The error message I see in CLI is: `In AbstractManagerRegistry.php line 149: Doctrine ORM Manager named "" does not exist.` 

Any idea what this could be?
No other changes happened, no other package got updated.
I've tested reverting back to `2.0.0` and everything works. Upgrading again to `2.1.0` and things are broken again.

### PR DESCRIPTION
**Pull request by alcaeus**
Fixes #283, #284

### CODE REVIEW

File: Command/Helper/DoctrineCommandHelper.php [hunk 1]
```diff
@@ -32,10 +33,12 @@ public static function setApplicationHelper(Application $application, InputInter
...
         $managerNames = $doctrine->getManagerNames();
 
-        if ($input->getOption('db') !== null || count($managerNames) === 0) {
-            self::setApplicationConnection($application, (string) $input->getOption('db'));
-        } else {
-            self::setApplicationEntityManager($application, (string) $input->getOption('em'));
+        $db = $input->getOption('db');
+        $em = $input->getOption('em');
+        if (is_string($db) || count($managerNames) === 0) {
+            self::setApplicationConnection($application, (string) $db);
```
Comment (andrew-demb) [inline Command/Helper/DoctrineCommandHelper.php]: Do not cast `$db` to string.
When project doesn't use `doctrine/orm` it will produce error `Doctrine ORM Connection named "" does not exist.`

Comment (alcaeus) [reply Command/Helper/DoctrineCommandHelper.php]: The `is_string` prevents that, but it's still wrong. The error stems from a documentation mistake in DoctrineBundle, which specifies the arguments as `string` where the underlying methods accept `string|null`. I'll fix that in a 1.11 patch release and ignore the error in the meantime

**Comment by emodric** [comment]
@alcaeus I'm still having the issue from #283 & #284, even with 2.1.1, as seen at https://travis-ci.com/netgen-layouts/layouts-core/jobs/256099758

**Comment by alcaeus** [comment]
I inadvertently merged this to master only. Give me a couple of minutes to fix my stupidity.

**Comment by emodric** [comment]
No worries :)

Thank you!

**Comment by nchagrass-bud** [comment]
Legend!
